# Generated by Django 3.2.3 on 2022-03-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category Name', max_length=100, verbose_name='Category name')),
                ('description', models.TextField(blank=True, help_text='Category Description', null=True, verbose_name='Category Description')),
                ('image', models.ImageField(help_text='Image for Category', upload_to='uploads/categories/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service Name', max_length=200, verbose_name='Service name')),
                ('description', models.TextField(blank=True, help_text='Service Description', null=True, verbose_name='Service Description')),
                ('image', models.ImageField(help_text='Image For Service', upload_to='uploads/services/', verbose_name='Service image')),
                ('category', models.ForeignKey(help_text='The Category Name of the Service', on_delete=django.db.models.deletion.CASCADE, to='services.category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(blank=True, help_text='size of the service', max_length=155, verbose_name='Size')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'verbose_name': 'Service Attribute',
                'verbose_name_plural': 'Service Attributes',
            },
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceattribute')),
            ],
            options={
                'verbose_name': 'Service Variant',
                'verbose_name_plural': 'Service Variants',
            },
        ),
    ]
