# Generated by Django 3.2 on 2022-01-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
