# Generated by Django 3.2 on 2022-02-14 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220215_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Category Description', null=True, verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text='Image for Category', upload_to='uploads/categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category Name', max_length=100, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text='The Category Name of the Service', on_delete=django.db.models.deletion.CASCADE, to='services.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Service Description', null=True, verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(help_text='Image For Service', upload_to='uploads/services/', verbose_name='Service image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Service Name', max_length=200, verbose_name='Service name'),
        ),
    ]
