# Generated by Django 3.1.6 on 2022-03-17 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220317_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
        migrations.AddField(
            model_name='order',
            name='modified_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
